/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.40
 * Generated at: 2025-05-09 09:12:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.*;
import dto.Cosmetics;
import dao.CosmeticsRepository;

public final class Addbeauty_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1746607818853L));
    _jspx_dependants.put("/header.jsp", Long.valueOf(1746607818853L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("dto.Cosmetics");
    _jspx_imports_classes.add("dao.CosmeticsRepository");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>상품추가</title>\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath() );
      out.write("/resources/css/beautyListstyle.css\">\r\n");
      out.write("<script src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/js/dday.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <header>\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"header-content\">\r\n");
      out.write("                <div class=\"logo\">K-<span>FOOD</span> GUIDE</div>\r\n");
      out.write("                <nav>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li><a href=\"#\">홈</a></li>\r\n");
      out.write("                        <li><a href=\"#\">한식(K-FOOD)</a></li>\r\n");
      out.write("                        <li><a href=\"#\">뷰티(K-BEAUTY)</a></li>\r\n");
      out.write("                        <li><a href=\"#\">관광지(TOURIST ATTRACTION)</a></li>\r\n");
      out.write("                        ");
 if (session.getAttribute("user") != null) { 
      out.write("\r\n");
      out.write("                            <li><a href=\"logout.jsp\">로그아웃</a></li>\r\n");
      out.write("                            <li><a href=\"mypage.jsp\">마이페이지</a></li>\r\n");
      out.write("                        ");
 } else { 
      out.write("\r\n");
      out.write("                            <li><a href=\"login.jsp\">로그인</a></li>\r\n");
      out.write("                            <li><a href=\"signin.jsp\">회원가입</a></li>\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </nav>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 배경 이미지 섹션 -->\r\n");
      out.write("<section class=\"bg-image\">\r\n");
      out.write("  <div class=\"overlay\">\r\n");
      out.write("\r\n");
      out.write("    <!-- 상품 추가 폼 -->\r\n");
      out.write("<div class=\"container pt-5 pb-5\">\r\n");
      out.write("  <h3 class=\"mb-4 text-start\">상품 등록</h3>\r\n");
      out.write("  <form action=\"add_cosmetics_process.jsp\" method=\"post\" enctype=\"multipart/form-data\" class=\"needs-validation\" novalidate>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"mb-3\">\r\n");
      out.write("      <label for=\"name\" class=\"form-label\">제품명</label>\r\n");
      out.write("      <input type=\"text\" class=\"form-control\" name=\"name\" id=\"name\" required>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"mb-3\">\r\n");
      out.write("      <label for=\"brand\" class=\"form-label\">브랜드</label>\r\n");
      out.write("      <input type=\"text\" class=\"form-control\" name=\"brand\" id=\"brand\" required>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"mb-3\">\r\n");
      out.write("      <label for=\"price\" class=\"form-label\">가격</label>\r\n");
      out.write("      <input type=\"number\" class=\"form-control\" name=\"price\" id=\"price\" required>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"mb-3\">\r\n");
      out.write("      <label for=\"main_ingredient\" class=\"form-label\">주요 성분</label>\r\n");
      out.write("      <input type=\"text\" class=\"form-control\" name=\"main_ingredient\" id=\"main_ingredient\" required>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"mb-3\">\r\n");
      out.write("      <label for=\"effect\" class=\"form-label\">효능</label>\r\n");
      out.write("      <input type=\"text\" class=\"form-control\" name=\"effect\" id=\"effect\" required>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"mb-3\">\r\n");
      out.write("      <label for=\"category\" class=\"form-label\">카테고리</label>\r\n");
      out.write("      <select class=\"form-select\" name=\"category\" id=\"category\" required>\r\n");
      out.write("        <option value=\"\">카테고리 선택</option>\r\n");
      out.write("        <option value=\"스킨케어\">스킨케어</option>\r\n");
      out.write("        <option value=\"메이크업\">메이크업</option>\r\n");
      out.write("        <option value=\"클렌징\">클렌징</option>\r\n");
      out.write("        <option value=\"헤어케어\">헤어케어</option>\r\n");
      out.write("      </select>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"mb-3\">\r\n");
      out.write("      <label for=\"image_file\" class=\"form-label\">제품 이미지 파일</label>\r\n");
      out.write("      <input type=\"file\" class=\"form-control\" name=\"image_file\" id=\"image_file\" accept=\"image/*\" required>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"text-end\">\r\n");
      out.write("      <button type=\"submit\" class=\"btn btn-primary\">등록</button>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("  </form>\r\n");
      out.write("</div>\r\n");
      out.write("    \r\n");
      out.write("  </div> <!-- overlay 끝 -->\r\n");
      out.write("</section> <!-- section 끝 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <footer>\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"footer-content\">\r\n");
      out.write("                <div class=\"footer-column\">\r\n");
      out.write("                    <h3>K-CULTURE GUIDE</h3>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li><a href=\"#\">소개</a></li>\r\n");
      out.write("                        <li><a href=\"#\">팀 소개</a></li>\r\n");
      out.write("                        <li><a href=\"#\">채용 정보</a></li>\r\n");
      out.write("                        <li><a href=\"#\">언론 보도</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"footer-column\">\r\n");
      out.write("                    <h3>가이드</h3>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li><a href=\"#\">음식 카테고리</a></li>\r\n");
      out.write("                        <li><a href=\"#\">지역별 맛집</a></li>\r\n");
      out.write("                        <li><a href=\"#\">추천 레스토랑</a></li>\r\n");
      out.write("                        <li><a href=\"#\">시즌 스페셜</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"footer-column\">\r\n");
      out.write("                    <h3>커뮤니티</h3>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li><a href=\"#\">포럼</a></li>\r\n");
      out.write("                        <li><a href=\"#\">이벤트</a></li>\r\n");
      out.write("                        <li><a href=\"#\">쿠킹 클래스</a></li>\r\n");
      out.write("                        <li><a href=\"#\">회원 혜택</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"footer-column\">\r\n");
      out.write("                    <h3>문의하기</h3>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li><a href=\"#\">고객 지원</a></li>\r\n");
      out.write("                        <li><a href=\"#\">제휴 문의</a></li>\r\n");
      out.write("                        <li><a href=\"#\">레스토랑 등록</a></li>\r\n");
      out.write("                        <li><a href=\"#\">피드백</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"copyright\">\r\n");
      out.write("                <p>&copy; 2025 K-FOOD GUIDE. All rights reserved.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>");
      out.write("\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
