/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.40
 * Generated at: 2025-05-09 06:32:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.*;
import dto.Cosmetics;
import dao.CosmeticsRepository;

public final class beautyCategory_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1746607818853L));
    _jspx_dependants.put("/header.jsp", Long.valueOf(1746607818853L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("dto.Cosmetics");
    _jspx_imports_classes.add("dao.CosmeticsRepository");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath() );
      out.write("/resources/css/beautyCategorystyle.css\">\r\n");
      out.write("<script src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/js/dday.js\"></script>\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css\" rel=\"stylesheet\">\r\n");
      out.write("<title>BeautyCategory</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <header>\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"header-content\">\r\n");
      out.write("                <div class=\"logo\">K-<span>FOOD</span> GUIDE</div>\r\n");
      out.write("                <nav>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li><a href=\"#\">홈</a></li>\r\n");
      out.write("                        <li><a href=\"#\">한식(K-FOOD)</a></li>\r\n");
      out.write("                        <li><a href=\"#\">뷰티(K-BEAUTY)</a></li>\r\n");
      out.write("                        <li><a href=\"#\">관광지(TOURIST ATTRACTION)</a></li>\r\n");
      out.write("                        ");
 if (session.getAttribute("user") != null) { 
      out.write("\r\n");
      out.write("                            <li><a href=\"logout.jsp\">로그아웃</a></li>\r\n");
      out.write("                            <li><a href=\"mypage.jsp\">마이페이지</a></li>\r\n");
      out.write("                        ");
 } else { 
      out.write("\r\n");
      out.write("                            <li><a href=\"login.jsp\">로그인</a></li>\r\n");
      out.write("                            <li><a href=\"signin.jsp\">회원가입</a></li>\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </nav>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 메인 이미지 -->\r\n");
      out.write("<div class=\"container-fluid p-0 text-center\" style=\"margin-top: 80px; position: relative;\">\r\n");
      out.write("  <img src=\"./resources/img/BEAUTY09.jpg\" class=\"img-fluid mx-auto\" alt=\"Your Image Description\" style=\"width: 1400px; height: 600px;\">\r\n");
      out.write("  \r\n");
      out.write("  <!-- 텍스트 오버레이 -->\r\n");
      out.write("  <div class=\"text-overlay\" style=\"position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%); color: white; font-size: 40px; font-weight: bold; text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.5);\">\r\n");
      out.write("    K - BEAUTY <br>\r\n");
      out.write("    Experience the Secrets of Korean Skincare\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- 배경 이미지 섹션 -->\r\n");
      out.write("<section class=\"bg-image\">	\r\n");
      out.write("<div class=\"overlay\">\r\n");
      out.write("<!-- 상품 카테고리1 섹션 -->\r\n");
      out.write("<div class=\"container pt-5 pb-3\" style=\"margin-bottom: 30px;\">\r\n");
      out.write("   <div class=\"d-flex justify-content-between align-items-center mb-4\">\r\n");
      out.write("    <h3 class=\"text-start mb-0\">Category1</h3>\r\n");
      out.write("    <a href=\"https://example.com\" class=\"btn btn-sm btn-outline-secondary\">\r\n");
      out.write("      더보기(More)\r\n");
      out.write("    </a>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"row row-cols-1 row-cols-md-4 gy-3 gx-3\">\r\n");
      out.write("  <!-- 카드1 -->\r\n");
      out.write("    <div class=\"col\">\r\n");
      out.write("      <div class=\"card h-100 shadow-sm border-0\" style=\"height: 280px;\"> <!-- style 위치 수정 -->\r\n");
      out.write("        <img src=\"./resources/img/makeup01.jpg\" class=\"card-img-top\" alt=\"...\" style=\"height: 200px; object-fit: cover;\">\r\n");
      out.write("        <div class=\"card-body p-2 text-center\" style=\"height: 80px; overflow: hidden;\"> <!-- 가운데 정렬 -->\r\n");
      out.write("          <h5 class=\"card-title mb-2\">Landscape & Cityscape</h5>\r\n");
      out.write("          <div class=\"d-flex justify-content-end gap-3 small text-muted mb-2\"> <!-- 가운데 정렬 -->\r\n");
      out.write("            <a href=\"#\" class=\"btn btn-sm btn-outline-primary\">상세보기</a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"card-footer bg-white border-0 text-end\"></div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("     <!-- 카드2 -->\r\n");
      out.write("    <div class=\"col\">\r\n");
      out.write("      <div class=\"card h-100 shadow-sm border-0\" style=\"height: 280px;\"> <!-- style 위치 수정 -->\r\n");
      out.write("        <img src=\"./resources/img/makeup02.jpg\" class=\"card-img-top\" alt=\"...\" style=\"height: 200px; object-fit: cover;\">\r\n");
      out.write("        <div class=\"card-body p-2 text-center\" style=\"height: 80px; overflow: hidden;\"> <!-- 가운데 정렬 -->\r\n");
      out.write("          <h5 class=\"card-title mb-2\">Landscape & Cityscape</h5>\r\n");
      out.write("          <div class=\"d-flex justify-content-end gap-3 small text-muted mb-2\"> <!-- 가운데 정렬 -->\r\n");
      out.write("            <a href=\"#\" class=\"btn btn-sm btn-outline-primary\">상세보기</a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"card-footer bg-white border-0 text-end\"></div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("     <!-- 카드3 -->\r\n");
      out.write("    <div class=\"col\">\r\n");
      out.write("      <div class=\"card h-100 shadow-sm border-0\" style=\"height: 280px;\"> <!-- style 위치 수정 -->\r\n");
      out.write("        <img src=\"./resources/img/makeup03.jpg\" class=\"card-img-top\" alt=\"...\" style=\"height: 200px; object-fit: cover;\">\r\n");
      out.write("        <div class=\"card-body p-2 text-center\" style=\"height: 80px; overflow: hidden;\"> <!-- 가운데 정렬 -->\r\n");
      out.write("          <h5 class=\"card-title mb-2\">Landscape & Cityscape</h5>\r\n");
      out.write("          <div class=\"d-flex justify-content-end gap-3 small text-muted mb-2\"> <!-- 가운데 정렬 -->\r\n");
      out.write("            <a href=\"#\" class=\"btn btn-sm btn-outline-primary\">상세보기</a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"card-footer bg-white border-0 text-end\"></div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("     <!-- 카드4 -->\r\n");
      out.write("    <div class=\"col\">\r\n");
      out.write("      <div class=\"card h-100 shadow-sm border-0\" style=\"height: 280px;\"> <!-- style 위치 수정 -->\r\n");
      out.write("        <img src=\"./resources/img/makeup04.jpg\" class=\"card-img-top\" alt=\"...\" style=\"height: 200px; object-fit: cover;\">\r\n");
      out.write("        <div class=\"card-body p-2 text-center\" style=\"height: 80px; overflow: hidden;\"> <!-- 가운데 정렬 -->\r\n");
      out.write("          <h5 class=\"card-title mb-2\">Landscape & Cityscape</h5>\r\n");
      out.write("          <div class=\"d-flex justify-content-end gap-3 small text-muted mb-2\"> <!-- 가운데 정렬 -->\r\n");
      out.write("            <a href=\"#\" class=\"btn btn-sm btn-outline-primary\">상세보기</a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"card-footer bg-white border-0 text-end\"></div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- 상품 카테고리2 섹션 -->\r\n");
      out.write("<div class=\"container p-2\" style=\"margin-bottom: 30px;\">\r\n");
      out.write("  <div class=\"d-flex justify-content-between align-items-center mb-4\">\r\n");
      out.write("    <h3 class=\"text-start mb-0\">Category2</h3>\r\n");
      out.write("    <a href=\"https://example.com\" class=\"btn btn-sm btn-outline-secondary\">\r\n");
      out.write("      더보기(More)\r\n");
      out.write("    </a>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"row row-cols-1 row-cols-md-4 gy-3 gx-3\">\r\n");
      out.write("  <!-- 카드1 -->\r\n");
      out.write("    <div class=\"col\">\r\n");
      out.write("      <div class=\"card h-100 shadow-sm border-0\" style=\"height: 280px;\"> <!-- style 위치 수정 -->\r\n");
      out.write("        <img src=\"./resources/img/makeup01.jpg\" class=\"card-img-top\" alt=\"...\" style=\"height: 200px; object-fit: cover;\">\r\n");
      out.write("        <div class=\"card-body p-2 text-center\" style=\"height: 80px; overflow: hidden;\"> <!-- 가운데 정렬 -->\r\n");
      out.write("          <h5 class=\"card-title mb-2\">Landscape & Cityscape</h5>\r\n");
      out.write("          <div class=\"d-flex justify-content-end gap-3 small text-muted mb-2\"> <!-- 가운데 정렬 -->\r\n");
      out.write("            <a href=\"#\" class=\"btn btn-sm btn-outline-primary\">상세보기</a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"card-footer bg-white border-0 text-end\"></div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("     <!-- 카드2 -->\r\n");
      out.write("    <div class=\"col\">\r\n");
      out.write("      <div class=\"card h-100 shadow-sm border-0\" style=\"height: 280px;\"> <!-- style 위치 수정 -->\r\n");
      out.write("        <img src=\"./resources/img/makeup02.jpg\" class=\"card-img-top\" alt=\"...\" style=\"height: 200px; object-fit: cover;\">\r\n");
      out.write("        <div class=\"card-body p-2 text-center\" style=\"height: 80px; overflow: hidden;\"> <!-- 가운데 정렬 -->\r\n");
      out.write("          <h5 class=\"card-title mb-2\">Landscape & Cityscape</h5>\r\n");
      out.write("          <div class=\"d-flex justify-content-end gap-3 small text-muted mb-2\"> <!-- 가운데 정렬 -->\r\n");
      out.write("            <a href=\"#\" class=\"btn btn-sm btn-outline-primary\">상세보기</a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"card-footer bg-white border-0 text-end\"></div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("     <!-- 카드3 -->\r\n");
      out.write("    <div class=\"col\">\r\n");
      out.write("      <div class=\"card h-100 shadow-sm border-0\" style=\"height: 280px;\"> <!-- style 위치 수정 -->\r\n");
      out.write("        <img src=\"./resources/img/makeup03.jpg\" class=\"card-img-top\" alt=\"...\" style=\"height: 200px; object-fit: cover;\">\r\n");
      out.write("        <div class=\"card-body p-2 text-center\" style=\"height: 80px; overflow: hidden;\"> <!-- 가운데 정렬 -->\r\n");
      out.write("          <h5 class=\"card-title mb-2\">Landscape & Cityscape</h5>\r\n");
      out.write("          <div class=\"d-flex justify-content-end gap-3 small text-muted mb-2\"> <!-- 가운데 정렬 -->\r\n");
      out.write("            <a href=\"#\" class=\"btn btn-sm btn-outline-primary\">상세보기</a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"card-footer bg-white border-0 text-end\"></div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("     <!-- 카드4 -->\r\n");
      out.write("    <div class=\"col\">\r\n");
      out.write("      <div class=\"card h-100 shadow-sm border-0\" style=\"height: 280px;\"> <!-- style 위치 수정 -->\r\n");
      out.write("        <img src=\"./resources/img/makeup04.jpg\" class=\"card-img-top\" alt=\"...\" style=\"height: 200px; object-fit: cover;\">\r\n");
      out.write("        <div class=\"card-body p-2 text-center\" style=\"height: 80px; overflow: hidden;\"> <!-- 가운데 정렬 -->\r\n");
      out.write("          <h5 class=\"card-title mb-2\">Landscape & Cityscape</h5>\r\n");
      out.write("          <div class=\"d-flex justify-content-end gap-3 small text-muted mb-2\"> <!-- 가운데 정렬 -->\r\n");
      out.write("            <a href=\"#\" class=\"btn btn-sm btn-outline-primary\">상세보기</a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"card-footer bg-white border-0 text-end\"></div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- 상품 카테고리3 섹션 -->\r\n");
      out.write("<div class=\"container p-2\" style=\"margin-bottom: 30px;\">\r\n");
      out.write("  <div class=\"d-flex justify-content-between align-items-center mb-4\">\r\n");
      out.write("    <h3 class=\"text-start mb-0\">Category3</h3>\r\n");
      out.write("    <a href=\"https://example.com\" class=\"btn btn-sm btn-outline-secondary\">\r\n");
      out.write("      더보기(More)\r\n");
      out.write("    </a>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"row row-cols-1 row-cols-md-4 gy-3 gx-3\">\r\n");
      out.write("  <!-- 카드1 -->\r\n");
      out.write("    <div class=\"col\">\r\n");
      out.write("      <div class=\"card h-100 shadow-sm border-0\" style=\"height: 280px;\"> <!-- style 위치 수정 -->\r\n");
      out.write("        <img src=\"./resources/img/makeup01.jpg\" class=\"card-img-top\" alt=\"...\" style=\"height: 200px; object-fit: cover;\">\r\n");
      out.write("        <div class=\"card-body p-2 text-center\" style=\"height: 80px; overflow: hidden;\"> <!-- 가운데 정렬 -->\r\n");
      out.write("          <h5 class=\"card-title mb-2\">Landscape & Cityscape</h5>\r\n");
      out.write("          <div class=\"d-flex justify-content-end gap-3 small text-muted mb-2\"> <!-- 가운데 정렬 -->\r\n");
      out.write("            <a href=\"#\" class=\"btn btn-sm btn-outline-primary\">상세보기</a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"card-footer bg-white border-0 text-end\"></div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("     <!-- 카드2 -->\r\n");
      out.write("    <div class=\"col\">\r\n");
      out.write("      <div class=\"card h-100 shadow-sm border-0\" style=\"height: 280px;\"> <!-- style 위치 수정 -->\r\n");
      out.write("        <img src=\"./resources/img/makeup02.jpg\" class=\"card-img-top\" alt=\"...\" style=\"height: 200px; object-fit: cover;\">\r\n");
      out.write("        <div class=\"card-body p-2 text-center\" style=\"height: 80px; overflow: hidden;\"> <!-- 가운데 정렬 -->\r\n");
      out.write("          <h5 class=\"card-title mb-2\">Landscape & Cityscape</h5>\r\n");
      out.write("          <div class=\"d-flex justify-content-end gap-3 small text-muted mb-2\"> <!-- 가운데 정렬 -->\r\n");
      out.write("            <a href=\"#\" class=\"btn btn-sm btn-outline-primary\">상세보기</a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"card-footer bg-white border-0 text-end\"></div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("     <!-- 카드3 -->\r\n");
      out.write("    <div class=\"col\">\r\n");
      out.write("      <div class=\"card h-100 shadow-sm border-0\" style=\"height: 280px;\"> <!-- style 위치 수정 -->\r\n");
      out.write("        <img src=\"./resources/img/makeup03.jpg\" class=\"card-img-top\" alt=\"...\" style=\"height: 200px; object-fit: cover;\">\r\n");
      out.write("        <div class=\"card-body p-2 text-center\" style=\"height: 80px; overflow: hidden;\"> <!-- 가운데 정렬 -->\r\n");
      out.write("          <h5 class=\"card-title mb-2\">Landscape & Cityscape</h5>\r\n");
      out.write("          <div class=\"d-flex justify-content-end gap-3 small text-muted mb-2\"> <!-- 가운데 정렬 -->\r\n");
      out.write("            <a href=\"#\" class=\"btn btn-sm btn-outline-primary\">상세보기</a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"card-footer bg-white border-0 text-end\"></div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("     <!-- 카드4 -->\r\n");
      out.write("    <div class=\"col\">\r\n");
      out.write("      <div class=\"card h-100 shadow-sm border-0\" style=\"height: 280px;\"> <!-- style 위치 수정 -->\r\n");
      out.write("        <img src=\"./resources/img/makeup04.jpg\" class=\"card-img-top\" alt=\"...\" style=\"height: 200px; object-fit: cover;\">\r\n");
      out.write("        <div class=\"card-body p-2 text-center\" style=\"height: 80px; overflow: hidden;\"> <!-- 가운데 정렬 -->\r\n");
      out.write("          <h5 class=\"card-title mb-2\">Landscape & Cityscape</h5>\r\n");
      out.write("          <div class=\"d-flex justify-content-end gap-3 small text-muted mb-2\"> <!-- 가운데 정렬 -->\r\n");
      out.write("            <a href=\"#\" class=\"btn btn-sm btn-outline-primary\">상세보기</a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"card-footer bg-white border-0 text-end\"></div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 상품 카테고리4 섹션 -->\r\n");
      out.write("<div class=\"container p-2\" style=\"margin-bottom: 30px;\">\r\n");
      out.write("  <div class=\"d-flex justify-content-between align-items-center mb-4\">\r\n");
      out.write("    <h3 class=\"text-start mb-0\">Category4</h3>\r\n");
      out.write("    <a href=\"https://example.com\" class=\"btn btn-sm btn-outline-secondary\">\r\n");
      out.write("      더보기(More)\r\n");
      out.write("    </a>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"row row-cols-1 row-cols-md-4 gy-3 gx-3\">\r\n");
      out.write("  <!-- 카드1 -->\r\n");
      out.write("    <div class=\"col\">\r\n");
      out.write("      <div class=\"card h-100 shadow-sm border-0\" style=\"height: 280px;\"> <!-- style 위치 수정 -->\r\n");
      out.write("        <img src=\"./resources/img/makeup01.jpg\" class=\"card-img-top\" alt=\"...\" style=\"height: 200px; object-fit: cover;\">\r\n");
      out.write("        <div class=\"card-body p-2 text-center\" style=\"height: 80px; overflow: hidden;\"> <!-- 가운데 정렬 -->\r\n");
      out.write("          <h5 class=\"card-title mb-2\">Landscape & Cityscape</h5>\r\n");
      out.write("          <div class=\"d-flex justify-content-end gap-3 small text-muted mb-2\"> <!-- 가운데 정렬 -->\r\n");
      out.write("            <a href=\"#\" class=\"btn btn-sm btn-outline-primary\">상세보기</a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"card-footer bg-white border-0 text-end\"></div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("     <!-- 카드2 -->\r\n");
      out.write("    <div class=\"col\">\r\n");
      out.write("      <div class=\"card h-100 shadow-sm border-0\" style=\"height: 280px;\"> <!-- style 위치 수정 -->\r\n");
      out.write("        <img src=\"./resources/img/makeup02.jpg\" class=\"card-img-top\" alt=\"...\" style=\"height: 200px; object-fit: cover;\">\r\n");
      out.write("        <div class=\"card-body p-2 text-center\" style=\"height: 80px; overflow: hidden;\"> <!-- 가운데 정렬 -->\r\n");
      out.write("          <h5 class=\"card-title mb-2\">Landscape & Cityscape</h5>\r\n");
      out.write("          <div class=\"d-flex justify-content-end gap-3 small text-muted mb-2\"> <!-- 가운데 정렬 -->\r\n");
      out.write("            <a href=\"#\" class=\"btn btn-sm btn-outline-primary\">상세보기</a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"card-footer bg-white border-0 text-end\"></div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("     <!-- 카드3 -->\r\n");
      out.write("    <div class=\"col\">\r\n");
      out.write("      <div class=\"card h-100 shadow-sm border-0\" style=\"height: 280px;\"> <!-- style 위치 수정 -->\r\n");
      out.write("        <img src=\"./resources/img/makeup03.jpg\" class=\"card-img-top\" alt=\"...\" style=\"height: 200px; object-fit: cover;\">\r\n");
      out.write("        <div class=\"card-body p-2 text-center\" style=\"height: 80px; overflow: hidden;\"> <!-- 가운데 정렬 -->\r\n");
      out.write("          <h5 class=\"card-title mb-2\">Landscape & Cityscape</h5>\r\n");
      out.write("          <div class=\"d-flex justify-content-end gap-3 small text-muted mb-2\"> <!-- 가운데 정렬 -->\r\n");
      out.write("            <a href=\"#\" class=\"btn btn-sm btn-outline-primary\">상세보기</a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"card-footer bg-white border-0 text-end\"></div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("     <!-- 카드4 -->\r\n");
      out.write("    <div class=\"col\">\r\n");
      out.write("      <div class=\"card h-100 shadow-sm border-0\" style=\"height: 280px;\"> <!-- style 위치 수정 -->\r\n");
      out.write("        <img src=\"./resources/img/makeup04.jpg\" class=\"card-img-top\" alt=\"...\" style=\"height: 200px; object-fit: cover;\">\r\n");
      out.write("        <div class=\"card-body p-2 text-center\" style=\"height: 80px; overflow: hidden;\"> <!-- 가운데 정렬 -->\r\n");
      out.write("          <h5 class=\"card-title mb-2\">Landscape & Cityscape</h5>\r\n");
      out.write("          <div class=\"d-flex justify-content-end gap-3 small text-muted mb-2\"> <!-- 가운데 정렬 -->\r\n");
      out.write("            <a href=\"#\" class=\"btn btn-sm btn-outline-primary\">상세보기</a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"card-footer bg-white border-0 text-end\"></div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div> <!-- .row 끝 -->\r\n");
      out.write("\r\n");
      out.write("</section> <!-- .section 끝 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <footer>\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"footer-content\">\r\n");
      out.write("                <div class=\"footer-column\">\r\n");
      out.write("                    <h3>K-CULTURE GUIDE</h3>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li><a href=\"#\">소개</a></li>\r\n");
      out.write("                        <li><a href=\"#\">팀 소개</a></li>\r\n");
      out.write("                        <li><a href=\"#\">채용 정보</a></li>\r\n");
      out.write("                        <li><a href=\"#\">언론 보도</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"footer-column\">\r\n");
      out.write("                    <h3>가이드</h3>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li><a href=\"#\">음식 카테고리</a></li>\r\n");
      out.write("                        <li><a href=\"#\">지역별 맛집</a></li>\r\n");
      out.write("                        <li><a href=\"#\">추천 레스토랑</a></li>\r\n");
      out.write("                        <li><a href=\"#\">시즌 스페셜</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"footer-column\">\r\n");
      out.write("                    <h3>커뮤니티</h3>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li><a href=\"#\">포럼</a></li>\r\n");
      out.write("                        <li><a href=\"#\">이벤트</a></li>\r\n");
      out.write("                        <li><a href=\"#\">쿠킹 클래스</a></li>\r\n");
      out.write("                        <li><a href=\"#\">회원 혜택</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"footer-column\">\r\n");
      out.write("                    <h3>문의하기</h3>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li><a href=\"#\">고객 지원</a></li>\r\n");
      out.write("                        <li><a href=\"#\">제휴 문의</a></li>\r\n");
      out.write("                        <li><a href=\"#\">레스토랑 등록</a></li>\r\n");
      out.write("                        <li><a href=\"#\">피드백</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"copyright\">\r\n");
      out.write("                <p>&copy; 2025 K-FOOD GUIDE. All rights reserved.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
