/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.40
 * Generated at: 2025-05-07 08:53:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1746607818853L));
    _jspx_dependants.put("/header.jsp", Long.valueOf(1746607818853L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>K-Food Guide - 한국 음식의 세계</title>\r\n");
      out.write("	<script src=\"./resources/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("	<link href=\"./resources/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./resources/css/index_style.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <header>\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"header-content\">\r\n");
      out.write("                <div class=\"logo\">K-<span>FOOD</span> GUIDE</div>\r\n");
      out.write("                <nav>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li><a href=\"#\">홈</a></li>\r\n");
      out.write("                        <li><a href=\"#\">한식(K-FOOD)</a></li>\r\n");
      out.write("                        <li><a href=\"#\">뷰티(K-BEAUTY)</a></li>\r\n");
      out.write("                        <li><a href=\"#\">관광지(TOURIST ATTRACTION)</a></li>\r\n");
      out.write("                        ");
 if (session.getAttribute("user") != null) { 
      out.write("\r\n");
      out.write("                            <li><a href=\"logout.jsp\">로그아웃</a></li>\r\n");
      out.write("                            <li><a href=\"mypage.jsp\">마이페이지</a></li>\r\n");
      out.write("                        ");
 } else { 
      out.write("\r\n");
      out.write("                            <li><a href=\"login.jsp\">로그인</a></li>\r\n");
      out.write("                            <li><a href=\"signin.jsp\">회원가입</a></li>\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </nav>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <section class=\"hero\">\r\n");
      out.write("		<div id=\"colorCarousel\" class=\"carousel slide\" data-bs-ride=\"carousel\">\r\n");
      out.write("			<div class=\"carousel-inner\">\r\n");
      out.write("		    	<div class=\"carousel-item active\">\r\n");
      out.write("					<img src=\"./resources/img/slideimg01.jpg\" class=\"d-block w-100\" alt=\"...\">\r\n");
      out.write("					<div class=\"fixed-caption\">\r\n");
      out.write("					  	<h3>K-FOOD</h3>\r\n");
      out.write("					  	<p>K-FOOD 한식 | 김치, 불고기, 비빔밥, 조미김, 불닭볶음면, 떡볶이</p>\r\n");
      out.write("					</div>\r\n");
      out.write("		    	</div>\r\n");
      out.write("		    	<div class=\"carousel-item\">\r\n");
      out.write("					<img src=\"./resources//img/slideimg02.jpg\" class=\"d-block w-100\" alt=\"...\">\r\n");
      out.write("					<div class=\"fixed-caption\">\r\n");
      out.write("					  	<h3>K-BEAUTY 한국의 뷰티 상품</h3>\r\n");
      out.write("					  	<p>Explore the rich and vibrant world of Korean culture!</p>\r\n");
      out.write("					</div>\r\n");
      out.write("		   		</div>\r\n");
      out.write("		    	<div class=\"carousel-item\">\r\n");
      out.write("					<img src=\"./resources//img/slideimg03.jpg\" class=\"d-block w-100\" alt=\"...\">\r\n");
      out.write("					<div class=\"fixed-caption\">\r\n");
      out.write("					  	<h3>TOURIST ATTRACTION</h3>\r\n");
      out.write("					  	<p>한국의 전통 관광지와 내 스타가 다녀간 장소들</p>\r\n");
      out.write("					</div>\r\n");
      out.write("		    	</div>\r\n");
      out.write("		  	</div>\r\n");
      out.write("		  	<button class=\"carousel-control-prev\" type=\"button\" data-bs-target=\"#colorCarousel\" data-bs-slide=\"prev\">\r\n");
      out.write("		    	<span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("		  	</button>\r\n");
      out.write("		  	<button class=\"carousel-control-next\" type=\"button\" data-bs-target=\"#colorCarousel\" data-bs-slide=\"next\">\r\n");
      out.write("			    <span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("		  	</button>\r\n");
      out.write("	  	</div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <section class=\"featured-section\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"section-title\">\r\n");
      out.write("                <h2>메인 카테고리</h2>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"food-grid\">\r\n");
      out.write("                ");
      out.write("\r\n");
      out.write("                <div class=\"food-card\">\r\n");
      out.write("                    <img src=\"./resources/img/KFOOD.JPG\" class=\"food-image\">\r\n");
      out.write("                    <div class=\"food-info\">\r\n");
      out.write("                        <h3>K-FOOD</h3>\r\n");
      out.write("                        <p>한국 음식(한식)에 대한 정보 나눔</p>\r\n");
      out.write("<!--                         <div class=\"rating\">\r\n");
      out.write("                            <span class=\"star\">★ ★ ★ ★ ★</span>\r\n");
      out.write("                            <span>(127 리뷰)</span>\r\n");
      out.write("                        </div> -->\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <span class=\"tag\">한식 레시피 나눔</span>\r\n");
      out.write("                            <span class=\"tag\">원데이 클래스 예약</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"food-card\">\r\n");
      out.write("                	<img src=\"./resources/img/BEAUTY01.jpg\" class=\"food-image\">\r\n");
      out.write("                    <div class=\"food-info\">\r\n");
      out.write("                        <h3>K-BEUATY</h3>\r\n");
      out.write("                        <p>한국의 화장품에 대한 정보 나눔</p>\r\n");
      out.write("<!--                         <div class=\"rating\">\r\n");
      out.write("                            <span class=\"star\">★ ★ ★ ★ ★</span>\r\n");
      out.write("                            <span>(98 리뷰)</span>\r\n");
      out.write("                        </div> -->\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <span class=\"tag\">화장품 정보</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"food-card\">\r\n");
      out.write("                    <img src=\"./resources/img/img (1).jpg\" class=\"food-image\">\r\n");
      out.write("                    <div class=\"food-info\">\r\n");
      out.write("                        <h3>TOURIST ATTRACTION</h3>\r\n");
      out.write("                        <p>한국 관광지에 대한 정보 나눔</p>\r\n");
      out.write("<!--                         <div class=\"rating\">\r\n");
      out.write("                            <span class=\"star\">★ ★ ★ ★ ★</span>\r\n");
      out.write("                            <span>(145 리뷰)</span>\r\n");
      out.write("                        </div> -->\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <span class=\"tag\">내 스타가 다녀간 곳</span>\r\n");
      out.write("                            <span class=\"tag\">전통 관광지</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <section class=\"about-section\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"about-content\">\r\n");
      out.write("                <div class=\"about-text\">\r\n");
      out.write("                    <h2>K-CULTURE</h2>\r\n");
      out.write("                    <p>K-CULTURE 한류 문화에 대한 정보 글 간단히 + 그래프? 같은거 넣으면 좋을듯</p>\r\n");
      out.write("                    <p>ㄹㅇㄹㅇ</p>\r\n");
      out.write("                    <p>ㅇㅈㅇㅈ</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"about-image\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <section class=\"community-section\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"section-title\">\r\n");
      out.write("                <h2>[사이트 이름] 사용법</h2>\r\n");
      out.write("                <p>사용법 어쩌고 저쩌고</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"community-cards\">\r\n");
      out.write("                <div class=\"community-card\">\r\n");
      out.write("                    <div class=\"community-icon\">👨‍👩‍👧‍👦</div>\r\n");
      out.write("                    <h3>정보 공유</h3>\r\n");
      out.write("                    <p>나만의 특별한 경험과 유익한 정보를 <br>다른 이들과 나눠보아요</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"community-card\">\r\n");
      out.write("                    <div class=\"community-icon\">🗺</div>\r\n");
      out.write("                    <h3>장소 찾기</h3>\r\n");
      out.write("                    <p>지도를 보며 체험 장소를 찾아보거나 <br>주변 맛집을 찾아보아요</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"community-card\">\r\n");
      out.write("                    <div class=\"community-icon\">✍</div>\r\n");
      out.write("                    <h3>체험 클래스</h3>\r\n");
      out.write("                    <p>다양한 원데이 클래스들을 골라 체험해 보아요</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("    <footer>\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"footer-content\">\r\n");
      out.write("                <div class=\"footer-column\">\r\n");
      out.write("                    <h3>K-CULTURE GUIDE</h3>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li><a href=\"#\">소개</a></li>\r\n");
      out.write("                        <li><a href=\"#\">팀 소개</a></li>\r\n");
      out.write("                        <li><a href=\"#\">채용 정보</a></li>\r\n");
      out.write("                        <li><a href=\"#\">언론 보도</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"footer-column\">\r\n");
      out.write("                    <h3>가이드</h3>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li><a href=\"#\">음식 카테고리</a></li>\r\n");
      out.write("                        <li><a href=\"#\">지역별 맛집</a></li>\r\n");
      out.write("                        <li><a href=\"#\">추천 레스토랑</a></li>\r\n");
      out.write("                        <li><a href=\"#\">시즌 스페셜</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"footer-column\">\r\n");
      out.write("                    <h3>커뮤니티</h3>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li><a href=\"#\">포럼</a></li>\r\n");
      out.write("                        <li><a href=\"#\">이벤트</a></li>\r\n");
      out.write("                        <li><a href=\"#\">쿠킹 클래스</a></li>\r\n");
      out.write("                        <li><a href=\"#\">회원 혜택</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"footer-column\">\r\n");
      out.write("                    <h3>문의하기</h3>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li><a href=\"#\">고객 지원</a></li>\r\n");
      out.write("                        <li><a href=\"#\">제휴 문의</a></li>\r\n");
      out.write("                        <li><a href=\"#\">레스토랑 등록</a></li>\r\n");
      out.write("                        <li><a href=\"#\">피드백</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"copyright\">\r\n");
      out.write("                <p>&copy; 2025 K-FOOD GUIDE. All rights reserved.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
