/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.40
 * Generated at: 2025-05-07 08:40:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class info01_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>K-Culture Info Site</title>\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath() );
      out.write("/resources/css/infostyle.css\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("  <!--  네비게이션 바 -->\r\n");
      out.write("  <nav class=\"navbar navbar-expand-lg\" style=\"background-color: #005BAC;\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <a class=\"navbar-brand text-white fw-bold\" href=\"#\">K-Culture INFO</a>\r\n");
      out.write("      <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarNav\">\r\n");
      out.write("        <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("      </button>\r\n");
      out.write("      <div class=\"collapse navbar-collapse\" id=\"navbarNav\">\r\n");
      out.write("        <ul class=\"navbar-nav ms-auto\">\r\n");
      out.write("          <li class=\"nav-item dropdown me-4\">\r\n");
      out.write("            <a class=\"nav-link dropdown-toggle text-white\" href=\"#\" role=\"button\" data-bs-toggle=\"dropdown\">K-FOOD</a>\r\n");
      out.write("            <ul class=\"dropdown-menu\">\r\n");
      out.write("              <li><a class=\"dropdown-item\" href=\"#\">Traditional Food</a></li>\r\n");
      out.write("              <li><a class=\"dropdown-item\" href=\"#\">Street Food</a></li>\r\n");
      out.write("              <li><a class=\"dropdown-item\" href=\"#\">Experience Program</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"nav-item dropdown me-4\">\r\n");
      out.write("            <a class=\"nav-link dropdown-toggle text-white\" href=\"#\" role=\"button\" data-bs-toggle=\"dropdown\">K-BEAUTY</a>\r\n");
      out.write("            <ul class=\"dropdown-menu\">\r\n");
      out.write("              <li><a class=\"dropdown-item\" href=\"#\">Skincare</a></li>\r\n");
      out.write("              <li><a class=\"dropdown-item\" href=\"#\">Makeup Trends</a></li>\r\n");
      out.write("              <li><a class=\"dropdown-item\" href=\"#\">Where to Buy</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"nav-item dropdown me-4\">\r\n");
      out.write("            <a class=\"nav-link dropdown-toggle text-white\" href=\"#\" role=\"button\" data-bs-toggle=\"dropdown\">LOCATION</a>\r\n");
      out.write("            <ul class=\"dropdown-menu\">\r\n");
      out.write("              <li><a class=\"dropdown-item\" href=\"#\">Seoul</a></li>\r\n");
      out.write("              <li><a class=\"dropdown-item\" href=\"#\">Busan</a></li>\r\n");
      out.write("              <li><a class=\"dropdown-item\" href=\"#\">Jeju</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <!--  단일 배너 이미지 + 중앙 텍스트 -->\r\n");
      out.write("<div class=\"position-relative text-white\" style=\"height: 400px; background: url('");
      out.print( request.getContextPath() );
      out.write("/resources/img/slideimg02.jpg') center/cover no-repeat;\">\r\n");
      out.write("  <div class=\"position-absolute top-50 start-50 translate-middle text-center\">\r\n");
      out.write("    <h1 class=\"fw-bold\">K-CULTURE 제품 소개</h1>\r\n");
      out.write("    <p class=\"fs-5\">한국 문화를 담은 특별한 제품들을 만나보세요</p>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <!--  메인 콘텐츠: 왼쪽 이미지 + 오른쪽 설명 -->\r\n");
      out.write("  <div class=\"container mt-5 mb-5\">\r\n");
      out.write("    <div class=\"row align-items-center\">\r\n");
      out.write("      <div class=\"col-md-6 d-flex justify-content-center\">\r\n");
      out.write("  			<img src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/img/ev02.jpg\" class=\"img-fluid rounded shadow\" style=\"width: 70%;\" alt=\"Product Main\">\r\n");
      out.write("	  </div>\r\n");
      out.write("      <div class=\"col-md-6\">\r\n");
      out.write("        <h3>전통 한과 세트</h3>\r\n");
      out.write("        <p class=\"lead\">정성껏 만든 한국의 전통 과자, 선물용으로도 좋고 가족과 나눠먹기에도 좋은 제품입니다.</p>\r\n");
      out.write("        <ul>\r\n");
      out.write("          <li>100% 국산 재료 사용</li>\r\n");
      out.write("          <li>전통 방식 수작업 제조</li>\r\n");
      out.write("          <li>선물용 포장 가능</li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <!-- 관련 이미지 -->\r\n");
      out.write("<div class=\"container mb-5\">\r\n");
      out.write("  <h4 class=\"mb-3\"></h4>\r\n");
      out.write("  <div class=\"d-flex flex-wrap film-strip\">\r\n");
      out.write("    <img src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/img/rg01.jpg\" class=\"img-thumbnail hover-zoom\" alt=\"related1\">\r\n");
      out.write("    <img src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/img/rg02.jpg\" class=\"img-thumbnail hover-zoom\" alt=\"related2\">\r\n");
      out.write("    <img src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/img/rg03.png\" class=\"img-thumbnail hover-zoom\" alt=\"related3\">\r\n");
      out.write("    <img src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/img/rg04.jpg\" class=\"img-thumbnail hover-zoom\" alt=\"related4\">\r\n");
      out.write("    <img src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/img/rg05.jpg\" class=\"img-thumbnail hover-zoom\" alt=\"related5\">\r\n");
      out.write("    <img src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/img/rg06.jpg\" class=\"img-thumbnail hover-zoom\" alt=\"related6\">\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <!-- 하단 네비바 -->\r\n");
      out.write("<div class=\"w-100 border-top small-nav\" style=\"height: 50px; background-color: #005BAC;\">\r\n");
      out.write("    <div class=\"d-flex justify-content-center align-items-center h-100\">\r\n");
      out.write("     <a class=\"mx-3 text-decoration-none fw-bold\" style=\"color: #fff;\">Posts</a>\r\n");
      out.write("     <a class=\"mx-3 text-decoration-none fw-bold\" style=\"color: #fff;\">View reserved </a>\r\n");
      out.write("     <a class=\"mx-3 text-decoration-none fw-bold\" style=\"color: #fff;\">View activity history</a>\r\n");
      out.write("     <a class=\"mx-3 text-decoration-none fw-bold\" style=\"color: #fff;\">Apply for experience</a>\r\n");
      out.write("     <a class=\"mx-3 text-decoration-none fw-bold\" style=\"color: #fff;\">View details</a>\r\n");
      out.write("    </div>\r\n");
      out.write("   </div>\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("  <!--  푸터 -->\r\n");
      out.write("  <footer class=\"text-center py-4 bg-light border-top\">\r\n");
      out.write("    <p>&copy; 2025 K-Culture Info. All rights reserved.</p>\r\n");
      out.write("  </footer>\r\n");
      out.write("\r\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
