/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.40
 * Generated at: 2025-05-08 00:07:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class reservation_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1746607818853L));
    _jspx_dependants.put("/header.jsp", Long.valueOf(1746607818853L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath() );
      out.write("/resources/css/reservationstyle.css\">\r\n");
      out.write("<title>reservation</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <header>\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"header-content\">\r\n");
      out.write("                <div class=\"logo\">K-<span>FOOD</span> GUIDE</div>\r\n");
      out.write("                <nav>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li><a href=\"#\">홈</a></li>\r\n");
      out.write("                        <li><a href=\"#\">한식(K-FOOD)</a></li>\r\n");
      out.write("                        <li><a href=\"#\">뷰티(K-BEAUTY)</a></li>\r\n");
      out.write("                        <li><a href=\"#\">관광지(TOURIST ATTRACTION)</a></li>\r\n");
      out.write("                        ");
 if (session.getAttribute("user") != null) { 
      out.write("\r\n");
      out.write("                            <li><a href=\"logout.jsp\">로그아웃</a></li>\r\n");
      out.write("                            <li><a href=\"mypage.jsp\">마이페이지</a></li>\r\n");
      out.write("                        ");
 } else { 
      out.write("\r\n");
      out.write("                            <li><a href=\"login.jsp\">로그인</a></li>\r\n");
      out.write("                            <li><a href=\"signin.jsp\">회원가입</a></li>\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </nav>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("<section class=\"hero\">\r\n");
      out.write("        <div class=\"hero-content\">\r\n");
      out.write("            <h1>한국 전통 음식을 통해 새로운 경험을 느껴보세요</h1>\r\n");
      out.write("            <p>한국 전통 방식을 체험하고, 즐겨보세요. GongGan과 함께 전통적인 한식의 세계로 초대합니다.</p>\r\n");
      out.write("            <a href=\"#\" class=\"hero_btn\">한식 체험 예약 하기</a>\r\n");
      out.write("        </div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<!-- 메인 콘텐츠: 왼쪽 이미지 + 오른쪽 설명 -->\r\n");
      out.write("<div class=\"container mt-5 mb-5\">\r\n");
      out.write("    <div class=\"row align-items-center\">\r\n");
      out.write("        <div class=\"col-md-6 d-flex justify-content-center\">\r\n");
      out.write("            <img src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/img/ev02.jpg\" class=\"img-fluid rounded shadow\" style=\"width: 70%;\" alt=\"Product Main\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-md-6\">\r\n");
      out.write("            <h3>전통 한과 만들기 체험</h3>\r\n");
      out.write("            <p class=\"lead\">정성 가득한 전통 한과를 직접 만들어보세요. 가족, 친구와 함께하는 특별한 체험으로 한국의 맛과 멋을 느낄 수 있습니다.</p>\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li>전통 방식의 한과 제조 과정을 직접 체험</li>\r\n");
      out.write("                <li>100% 국산 재료로 안전하고 건강하게</li>\r\n");
      out.write("                <li>완성된 한과는 예쁜 포장으로 가져가기 가능</li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- 관련 이미지 -->\r\n");
      out.write("<div class=\"container mb-5\">\r\n");
      out.write("    <h4 class=\"mb-3\"></h4>\r\n");
      out.write("    <div class=\"d-flex flex-wrap film-strip\">\r\n");
      out.write("        <img src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/img/rg01.jpg\" class=\"img-thumbnail hover-zoom\" alt=\"related1\">\r\n");
      out.write("        <img src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/img/rg02.jpg\" class=\"img-thumbnail hover-zoom\" alt=\"related2\">\r\n");
      out.write("        <img src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/img/rg03.png\" class=\"img-thumbnail hover-zoom\" alt=\"related3\">\r\n");
      out.write("        <img src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/img/rg04.jpg\" class=\"img-thumbnail hover-zoom\" alt=\"related4\">\r\n");
      out.write("        <img src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/img/rg05.jpg\" class=\"img-thumbnail hover-zoom\" alt=\"related5\">\r\n");
      out.write("        <img src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/img/rg06.jpg\" class=\"img-thumbnail hover-zoom\" alt=\"related6\">\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 체험 세부 정보칸 -->\r\n");
      out.write("<div class=\"container mt-5 mb-5\">\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("        <div class=\"col-md-12\">\r\n");
      out.write("            <h4 class=\"mb-3 text-center\">Experience Details</h4>\r\n");
      out.write("            <table class=\"table table-bordered\">\r\n");
      out.write("                <tbody>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th scope=\"row\" class=\"bg-light\">체험 내용</th>\r\n");
      out.write("                        <td>전통 한과 (유과, 강정 등) 만들기</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th scope=\"row\" class=\"bg-light\">소요 시간</th>\r\n");
      out.write("                        <td>약 2시간</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th scope=\"row\" class=\"bg-light\">체험 장소</th>\r\n");
      out.write("                        <td>[정확한 주소] <br> (대중교통 이용 시: [가까운 지하철역/버스 정류장]에서 [도보/버스] [소요 시간]) <br> (주차 가능 여부: [가능/불가능])</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th scope=\"row\" class=\"bg-light\">참가 비용</th>\r\n");
      out.write("                        <td>성인 30,000원 / 아동 20,000원</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th scope=\"row\" class=\"bg-light\">포함 사항</th>\r\n");
      out.write("                        <td>재료비, 포장재, 체험 지도</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th scope=\"row\" class=\"bg-light\">최대 인원</th>\r\n");
      out.write("                        <td>10명</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th scope=\"row\" class=\"bg-light\">예약 변경 및 취소</th>\r\n");
      out.write("                        <td>[예약 변경 및 취소 가능 기한 및 방법], [취소 시 환불 규정]</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th scope=\"row\" class=\"bg-light\">추가 안내 사항</th>\r\n");
      out.write("                        <td>[알레르기 관련 주의 사항]</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                </tbody>\r\n");
      out.write("            </table>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- 체험자 후기칸 - 카드로 구성 - 게시판 연동 필요 -->\r\n");
      out.write("<div class=\"container mb-5\">\r\n");
      out.write("    <h4 class=\"mb-4 text-center\">Review</h4>\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("        <!-- 후기 카드 1 -->\r\n");
      out.write("        <div class=\"col-md-4 mb-4\">\r\n");
      out.write("            <div class=\"card h-100 shadow-sm\">\r\n");
      out.write("                <img src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/img/exs01.jpg\" class=\"card-img-top review-img\" alt=\"\">\r\n");
      out.write("                <div class=\"card-body\">\r\n");
      out.write("                    <h5 class=\"card-title\">Mike0543</h5>\r\n");
      out.write("                    <p class=\"card-text\">Lorem Ipsum is simply dummy text of the printing and typesetting industry. \r\n");
      out.write("                    Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, \r\n");
      out.write("                    when an unknown printer took a galley of type and scrambled it to make a type specimen book..</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"card-footer text-muted text-end\">\r\n");
      out.write("                    2025년 5월 5일\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- 후기 카드 2 -->\r\n");
      out.write("        <div class=\"col-md-4 mb-4\">\r\n");
      out.write("            <div class=\"card h-100 shadow-sm\">\r\n");
      out.write("                <img src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/img/exs02.jpg\" class=\"card-img-top review-img\" alt=\"\">\r\n");
      out.write("                <div class=\"card-body\">\r\n");
      out.write("                    <h5 class=\"card-title\">selon0117</h5>\r\n");
      out.write("                    <p class=\"card-text\">t is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"card-footer text-muted text-end\">\r\n");
      out.write("                    2025년 5월 3일\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <!-- 후기 카드 3 -->\r\n");
      out.write("        <div class=\"col-md-4 mb-4\">\r\n");
      out.write("            <div class=\"card h-100 shadow-sm\">\r\n");
      out.write("                <img src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/img/exs03.jpg\" class=\"card-img-top review-img\" alt=\"\">\r\n");
      out.write("                <div class=\"card-body\">\r\n");
      out.write("                    <h5 class=\"card-title\">jamie123</h5>\r\n");
      out.write("                    <p class=\"card-text\">Contrary to popular belief, Lorem Ipsum is not simply random text. \r\n");
      out.write("                    It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock,</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"card-footer text-muted text-end\">\r\n");
      out.write("                    2025년 5월 3일\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 예약하기 섹션 -->\r\n");
      out.write("<div class=\"container mb-5\">\r\n");
      out.write("    <div class=\"bg-light p-4 rounded shadow-sm\">\r\n");
      out.write("        <h4 class=\"mb-4 text-center\">전통 한과 만들기 체험 예약</h4>\r\n");
      out.write("        <form action=\"reservationDetail.jsp\" method=\"post\">\r\n");
      out.write("            <div class=\"text-center mt-4\">\r\n");
      out.write("                <button type=\"submit\" class=\"btn btn-primary px-4 py-2 me-3\">예약하기</button>\r\n");
      out.write("                <a href=\"javascript:history.back()\" class=\"btn btn-success px-4 py-2\">뒤로가기</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <footer>\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"footer-content\">\r\n");
      out.write("                <div class=\"footer-column\">\r\n");
      out.write("                    <h3>K-CULTURE GUIDE</h3>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li><a href=\"#\">소개</a></li>\r\n");
      out.write("                        <li><a href=\"#\">팀 소개</a></li>\r\n");
      out.write("                        <li><a href=\"#\">채용 정보</a></li>\r\n");
      out.write("                        <li><a href=\"#\">언론 보도</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"footer-column\">\r\n");
      out.write("                    <h3>가이드</h3>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li><a href=\"#\">음식 카테고리</a></li>\r\n");
      out.write("                        <li><a href=\"#\">지역별 맛집</a></li>\r\n");
      out.write("                        <li><a href=\"#\">추천 레스토랑</a></li>\r\n");
      out.write("                        <li><a href=\"#\">시즌 스페셜</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"footer-column\">\r\n");
      out.write("                    <h3>커뮤니티</h3>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li><a href=\"#\">포럼</a></li>\r\n");
      out.write("                        <li><a href=\"#\">이벤트</a></li>\r\n");
      out.write("                        <li><a href=\"#\">쿠킹 클래스</a></li>\r\n");
      out.write("                        <li><a href=\"#\">회원 혜택</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"footer-column\">\r\n");
      out.write("                    <h3>문의하기</h3>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li><a href=\"#\">고객 지원</a></li>\r\n");
      out.write("                        <li><a href=\"#\">제휴 문의</a></li>\r\n");
      out.write("                        <li><a href=\"#\">레스토랑 등록</a></li>\r\n");
      out.write("                        <li><a href=\"#\">피드백</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"copyright\">\r\n");
      out.write("                <p>&copy; 2025 K-FOOD GUIDE. All rights reserved.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
